from backend.env import env
# SENDGRID_API_KEY = env('SENDGRID_API_KEY')
# DEFAULT_FROM_EMAIL = env('SENDGRID_DEFAULT_FROM_EMAIL')
# CONTACT_EMAIL_RECEIVER = env('SENDGRID_CONTACT_EMAIL_RECEIVER')

# AWS_ACCESS_KEY_ID=env('AWS_ACCESS_KEY_ID')
# AWS_SECRET_ACCESS_KEY=env('AWS_SECRET_ACCESS_KEY')
# AWS_DEFAULT_REGION=env('AWS_DEFAULT_REGION')

RESEND_API_KEY = env('RESEND_API_KEY')