# Generated by Django 5.2.5 on 2025-08-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=25)),
                ('language_proficiency', models.CharField(choices=[('elementary', 'Elementary'), ('limited', 'Limited'), ('fluent', 'Fluent')], default='elementary', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Expertise',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='name',
            new_name='skill_name',
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('uncategorized', '--Uncategorized--'), ('professional', 'Professional'), ('technical', 'Technical')], default='uncategorized', max_length=20),
        ),
    ]
