# Generated by Django 5.2.5 on 2025-08-26 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_education_certificate_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='language',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='language_proficiency',
            new_name='proficiency',
        ),
    ]
