# Generated by Django 5.2.5 on 2025-09-02 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_rename_language_language_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill_type',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skill_name',
            new_name='name',
        ),
    ]
